AllCops:
  TargetRubyVersion: 2.7.0
  DisplayCopNames: true
  Exclude:
    - '**/*.yml'
    - 'db/**/*'
    - 'config/**/*'
    - 'doc/**/*'
    - 'deployment/**/*'
    - 'bin/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/dummy/db/**/*'
    - 'spec/dummy/config/**/*'
    - 'test/**/*'

Style/StringLiterals:
  Enabled: false

Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/DotPosition:
  EnforcedStyle: trailing

Style/FormatString:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'spec/**/*'

Style/StringLiteralsInInterpolation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Layout/CaseIndentation:
  # Valid values are: case, end
  EnforcedStyle: end
  IndentOneStep: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ParameterLists:
  Max: 10

Lint/UselessAssignment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Rails:
  Enabled: true
